name: Build and Save PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Docker Compose
      run: docker-compose run convert

    - name: Save PDF as artifact
      uses: actions/upload-artifact@v2
      with:
        name: nextjs_docs.pdf
        path: ./dist/nextjs_docs.pdf
