name: On Push

on: [push]

jobs:
  build:
    uses: ./.github/workflows/job_convert_docs.yml
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  deploy:
    uses: ./.github/workflows/job_release.yml
    needs: build
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
